### ISSUE TITLE
Cloudflare: Broken link

### ISSUE THREAD

**Issue by theMosaad** [opennextjs/docs#11]
Fyi, link to the comparison between `@opennextjs/cloudflare` and `@cloudflare/next-on-pages` is the word `LINK`
https://github.com/opennextjs/docs/blob/b880a6cc161ec39790687cefa1d4355880e680e3/pages/cloudflare/index.mdx?plain=1#L11

**Comment by dario-piotrowicz** [comment]
@theMosaad Thanks for flagging this 🙂👍

It seems like the link has already been fixed, but it does not point to somewhat wrong page: https://developers.cloudflare.com/workers/static-assets/compatibility-matrix/

I'll bring this to the team 👍

**Comment by dario-piotrowicz** [comment]
@theMosaad the above should have been fixed by #20 🙂 

Closing this issue as it should be all good now, please feel free to reopen it or open a new one if you spot other problem

thanks again 🙂
